stages:
  train:
    cmd: python pipeline/train_pipeline.py
    deps:
    - config.py
    - pipeline/train_pipeline.py
    - src/feature_engineering.py
    outs:
    - data/processed/reference_data.csv
    - pipeline/models/latest_model.json